import './globals.css'
import { Montserrat, Poppins, Lato } from 'next/font/google'

import TopNav from '@/Components/TopNav'
import { options } from '@/Components/BarChart'


const lato = Lato({ subsets: ['latin'], weight: '700', variable: '--font-lato',})
const poppins = Poppins({subsets: ['latin'],  weight: '400', variable: '--font-poppins'}) 
const montserrat = Montserrat({subsets: ['latin'], weight: '400', variable: '--font-montserrat'}) 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}><TopNav/>{children}</body>
    </html>
  )
}
